# Data cleaning

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
df_customers = pd.read_csv('../data/raw/customers.csv', low_memory=False)
df_discounts = pd.read_csv('../data/raw/discounts.csv', low_memory=False)
df_employees = pd.read_csv('../data/raw/employees.csv', low_memory=False)
df_products = pd.read_csv('../data/raw/products.csv', low_memory=False)
df_stores = pd.read_csv('../data/raw/stores.csv', low_memory=False)
df_transactions = pd.read_csv('../data/raw/transactions.csv', low_memory=False)

**Customer table**

In [3]:
df_customers.head()

,Customer ID,Name,Email,Telephone,City,Country,Gender,Date Of Birth,Job Title
0,1,Tyler Garcia,tyler.garcia@fake_gmail.com,922.970.2265x47563,New York,United States,M,2003-07-15,NaN
1,2,Joshua Miller,joshua.miller@fake_gmail.com,+1-958-729-6169,New York,United States,M,2000-06-16,Records manager
2,3,Alison Marshall DDS,alison.marshall.dds@fake_hotmail.com,+1-645-567-0876x5409,New York,United States,F,2003-07-22,NaN
3,4,Jeffery Acosta,jeffery.acosta@fake_yahoo.com,212.336.0912x84994,New York,United States,M,1996-11-12,Proofreader
4,5,Ashley Sanders,ashley.sanders@fake_hotmail.com,7814535781,New York,United States,F,1998-02-10,Exercise physiologist

In [4]:
df_customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 1643306 entries, 0 to 1643305
Data columns (total 9 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Customer ID    1643306 non-null  int64
 1   Name           1643306 non-null  str
 2   Email          1643306 non-null  str
 3   Telephone      1643306 non-null  str
 4   City           1643306 non-null  str
 5   Country        1643306 non-null  str
 6   Gender         1643306 non-null  str
 7   Date Of Birth  1643306 non-null  str
 8   Job Title      1059121 non-null  str
dtypes: int64(1), str(8)
memory usage: 112.8 MB

In [5]:
df_customers.isnull().sum()

Customer ID           0
Name                  0
Email                 0
Telephone             0
City                  0
Country               0
Gender                0
Date Of Birth         0
Job Title        584185
dtype: int64

In [6]:
df_customers['Job Title'] = df_customers['Job Title'].fillna(' ')

In [7]:
df_customers['Gender'].unique()

<StringArray>
['M', 'F', 'D']
Length: 3, dtype: str

In [8]:
df_customers.columns = df_customers.columns.str.lower().str.replace(' ', '_')

**Discount table**

In [9]:
df_discounts.head()

,Start,End,Discont,Description,Category,Sub Category
0,2020-01-01,2020-01-10,0.4,40% discount during our New Year Winter Sale,Feminine,Coats and Blazers
1,2020-01-01,2020-01-10,0.4,40% discount during our New Year Winter Sale,Feminine,Sweaters and Knitwear
2,2020-01-01,2020-01-10,0.4,40% discount during our New Year Winter Sale,Masculine,Coats and Blazers
3,2020-01-01,2020-01-10,0.4,40% discount during our New Year Winter Sale,Masculine,Sweaters and Sweatshirts
4,2020-01-01,2020-01-10,0.4,40% discount during our New Year Winter Sale,Children,Coats

In [10]:
df_discounts.info()

<class 'pandas.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Start         181 non-null    str
 1   End           181 non-null    str
 2   Discont       181 non-null    float64
 3   Description   181 non-null    str
 4   Category      171 non-null    str
 5   Sub Category  171 non-null    str
dtypes: float64(1), str(5)
memory usage: 8.6 KB

In [11]:
df_discounts.columns = df_discounts.columns.str.lower().str.replace(' ', '_')

In [12]:
df_discounts['category'].unique()

<StringArray>
['Feminine', 'Masculine', 'Children', nan]
Length: 4, dtype: str

In [13]:
df_discounts['sub_category'].unique()

<StringArray>
[                   'Coats and Blazers',
                'Sweaters and Knitwear',
             'Sweaters and Sweatshirts',
                                'Coats',
                             'Sweaters',
                'Dresses and Jumpsuits',
                   'Shirts and Blouses',
                   'T-shirts and Polos',
                               'Shirts',
 'Girl and Boy (1-5 years, 6-14 years)',
                    'T-shirts and Tops',
                    'Skirts and Shorts',
                      'Pants and Jeans',
                              'Pajamas',
                          'Accessories',
                           'Sportswear',
                                    nan]
Length: 17, dtype: str

In [14]:
df_discounts['start'] = pd.to_datetime(df_discounts['start']) # convert from object to datetime
df_discounts['end'] = pd.to_datetime(df_discounts['end'])

In [15]:
df_discounts['discont']=df_discounts['discont']/ 100

**Product table**

In [16]:
df_products.head()

,Product ID,Category,Sub Category,Description PT,Description DE,Description FR,Description ES,Description EN,Description ZH,Color,Sizes,Production Cost
0,1,Feminine,Coats and Blazers,Esportivo Veludo Verde Com Botões,Sport Samt Sport Mit Knöpfen,Sports Velvet Sports Avec Des Boutons,Deportes De Terciopelo Con Botones,Sports Velvet Sports With Buttons,运动天鹅绒运动与按钮,NaN,S|M|L|XL,10.73
1,2,Feminine,Sweaters and Knitwear,Luxuoso Denim Rosa Com Botões,Luxuriöser Rosa Jeans Mit Knöpfen,Léchard De Denim Rose Avec Boutons,Denim Rosa Lujoso Con Botones,Luxurious Pink Denim With Buttons,豪华的粉红色牛仔布和纽扣,PINK,S|M|L|XL,19.55
2,3,Feminine,Dresses and Jumpsuits,Retrô Tricot Preto Estampado,Black Tricot Gedruckter Tricot,Tricot Imprimé En Tricot Noir,Tricot Negro Tricot Impreso,Black Tricot Printed Tricot,黑色三角形印刷三角形,BLACK,S|M|L|XL,25.59
3,4,Feminine,Shirts and Blouses,Blusa De Algodão Básica,Basis -Baumwollbluse,Chemisier En Coton De Base,Blusa De Algodón,Basic Cotton Blouse,基本的棉衬衫,NaN,S|M|L|XL,27.62
4,5,Feminine,T-shirts and Tops,T-Shirt Básica De Algodão,Basis-Baumwoll-T-Shirt,T-Shirt En Coton De Base,Camiseta Básica De Algodón,Basic Cotton T-Shirt,基本棉T恤,NaN,S|M|L,11.69

In [18]:
df_products = df_products.drop(columns=['Description ES','Description FR','Description DE','Description PT','Description ZH'])

In [19]:
df_products.columns = df_products.columns.str.lower().str.replace(' ', '_')

In [20]:
df_products['category'].unique()

<StringArray>
['Feminine', 'Masculine', 'Children']
Length: 3, dtype: str

In [21]:
df_products['sub_category'].unique()

<StringArray>
[                   'Coats and Blazers',
                'Sweaters and Knitwear',
                'Dresses and Jumpsuits',
                   'Shirts and Blouses',
                    'T-shirts and Tops',
                      'Pants and Jeans',
                    'Skirts and Shorts',
                       'Suits and Sets',
                           'Sportswear',
                 'Lingerie and Pajamas',
                          'Accessories',
             'Sweaters and Sweatshirts',
                   'T-shirts and Polos',
                               'Shirts',
                    'Suits and Blazers',
                'Underwear and Pajamas',
                   'Baby (0-12 months)',
 'Girl and Boy (1-5 years, 6-14 years)',
                                'Coats',
                             'Sweaters',
                              'Pajamas']
Length: 21, dtype: str

In [25]:
df_products

,product_id,category,sub_category,description_en,color,sizes,production_cost
0,1,Feminine,Coats and Blazers,Sports Velvet Sports With Buttons,NaN,S|M|L|XL,10.73
1,2,Feminine,Sweaters and Knitwear,Luxurious Pink Denim With Buttons,PINK,S|M|L|XL,19.55
2,3,Feminine,Dresses and Jumpsuits,Black Tricot Printed Tricot,BLACK,S|M|L|XL,25.59
3,4,Feminine,Shirts and Blouses,Basic Cotton Blouse,NaN,S|M|L|XL,27.62
4,5,Feminine,T-shirts and Tops,Basic Cotton T-Shirt,NaN,S|M|L,11.69
...,...,...,...,...,...,...,...
17935,17936,Children,"Girl and Boy (1-5 years, 6-14 years)",Executive Green Suede With Zipper,GREEN,P|M|G|GG,7.69
17936,17937,Children,Coats,Luxurious Turquoise Wool With Hood,TURQUOISE,P|M|G,11.65
17937,17938,Children,Sweaters,Kidskot Shirt With Geometric Print,NaN,P|M|G,24.38
17938,17939,Children,Pajamas,Kids Satin Pajama With Smooth Shine And Pocket,NaN,P|M|G,18.27
17939,17940,Children,Accessories,Children'S Arm Protector For Safety,NaN,NaN,10.99

**Store table**

In [26]:
df_stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Store ID             35 non-null     int64
 1   Country              35 non-null     str
 2   City                 35 non-null     str
 3   Store Name           35 non-null     str
 4   Number of Employees  35 non-null     int64
 5   ZIP Code             35 non-null     str
 6   Latitude             35 non-null     float64
 7   Longitude            35 non-null     float64
dtypes: float64(2), int64(2), str(4)
memory usage: 2.3 KB

In [27]:
df_stores.columns = df_stores.columns.str.lower().str.replace(' ', '_')

**Transaction table**

In [28]:
df_transactions.head()

,Invoice ID,Line,Customer ID,Product ID,Size,Color,Unit Price,Quantity,Date,Discount,Line Total,Store ID,Employee ID,Currency,Currency Symbol,SKU,Transaction Type,Payment Method,Invoice Total
0,INV-US-001-03558761,1,47162,485,M,NaN,80.5,1,2023-01-01 15:42:00,0.0,80.5,1,7,USD,$,MASU485-M-,Sale,Cash,126.7
1,INV-US-001-03558761,2,47162,2779,G,NaN,31.5,1,2023-01-01 15:42:00,0.4,18.9,1,7,USD,$,CHCO2779-G-,Sale,Cash,126.7
2,INV-US-001-03558761,3,47162,64,M,NEUTRAL,45.5,1,2023-01-01 15:42:00,0.4,27.3,1,7,USD,$,MACO64-M-NEUTRAL,Sale,Cash,126.7
3,INV-US-001-03558762,1,10142,131,M,BLUE,70.0,1,2023-01-01 20:04:00,0.4,42.0,1,6,USD,$,FECO131-M-BLUE,Sale,Cash,77.0
4,INV-US-001-03558762,2,10142,716,L,WHITE,26.0,1,2023-01-01 20:04:00,0.0,26.0,1,6,USD,$,MAT-716-L-WHITE,Sale,Cash,77.0

In [29]:
df_transactions.columns = df_transactions.columns.str.lower().str.replace(' ', '_')

In [30]:
df_transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 6416827 entries, 0 to 6416826
Data columns (total 19 columns):
 #   Column            Dtype
---  ------            -----
 0   invoice_id        str
 1   line              int64
 2   customer_id       int64
 3   product_id        int64
 4   size              str
 5   color             str
 6   unit_price        float64
 7   quantity          int64
 8   date              str
 9   discount          float64
 10  line_total        float64
 11  store_id          int64
 12  employee_id       int64
 13  currency          str
 14  currency_symbol   str
 15  sku               str
 16  transaction_type  str
 17  payment_method    str
 18  invoice_total     float64
dtypes: float64(4), int64(6), str(9)
memory usage: 930.2 MB

In [31]:
df_transactions['date'] = pd.to_datetime(df_transactions['date']) # convert from object to datetime

In [32]:
df_transactions['Month'] = df_transactions['date'].dt.month #new column
df_transactions['Year'] = df_transactions['date'].dt.year
df_transactions['Day'] = df_transactions['date'].dt.dayofweek

In [33]:
df_transactions.isna().sum() # not relevant for business focus

invoice_id                0
line                      0
customer_id               0
product_id                0
size                 413102
color               4350783
unit_price                0
quantity                  0
date                      0
discount                  0
line_total                0
store_id                  0
employee_id               0
currency                  0
currency_symbol           0
sku                       0
transaction_type          0
payment_method            0
invoice_total             0
Month                     0
Year                      0
Day                       0
dtype: int64

## Data wrangling - unique fact table

In [34]:
df= df_transactions.merge(df_products, on = 'product_id', how = 'left')
df

,invoice_id,line,customer_id,product_id,size,color_x,unit_price,quantity,date,discount,...,invoice_total,Month,Year,Day,category,sub_category,description_en,color_y,sizes,production_cost
0,INV-US-001-03558761,1,47162,485,M,NaN,80.5,1,2023-01-01 15:42:00,0.00,...,126.70,1,2023,6,Masculine,Suits and Blazers,Men'S Rustic Fabric Blazer With Texture,NaN,M|L|XL,12.09
1,INV-US-001-03558761,2,47162,2779,G,NaN,31.5,1,2023-01-01 15:42:00,0.40,...,126.70,1,2023,6,Children,Coats,Streetwear Golden Silk,NaN,P|M|G,15.14
2,INV-US-001-03558761,3,47162,64,M,NEUTRAL,45.5,1,2023-01-01 15:42:00,0.40,...,126.70,1,2023,6,Masculine,Coats and Blazers,Luxurious Neutral Suede With Hood,NEUTRAL,M|L|XL|XXL,12.02
3,INV-US-001-03558762,1,10142,131,M,BLUE,70.0,1,2023-01-01 20:04:00,0.40,...,77.00,1,2023,6,Feminine,Coats and Blazers,Formal Blue Jeans With Ruffles,BLUE,S|M|L|XL,49.28
4,INV-US-001-03558762,2,10142,716,L,WHITE,26.0,1,2023-01-01 20:04:00,0.00,...,77.00,1,2023,6,Masculine,T-shirts and Polos,High-Tech Suede White Embroidered,WHITE,M|L|XL,8.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6416822,INV-PT-035-01497756,2,1640168,15414,P,NaN,35.5,1,2025-03-18 08:52:00,0.35,...,69.55,3,2025,1,Children,"Girl and Boy (1-5 years, 6-14 years)",Boho Jacquard Bege,NaN,P|M|G|GG,3.67
6416823,INV-PT-035-01497756,3,1640168,15232,G,RED,51.5,1,2025-03-18 08:52:00,0.35,...,69.55,3,2025,1,Children,"Girl and Boy (1-5 years, 6-14 years)",High-Tech Red Denim With Ruffles,RED,P|M|G,26.46
6416824,INV-PT-035-01497757,1,1636770,15401,XL,NaN,40.0,1,2025-03-18 19:01:00,0.00,...,40.00,3,2025,1,Feminine,Sportswear,Female Yoga Shorts,NaN,S|M|L|XL,6.92
6416825,INV-PT-035-01497758,1,1642472,15671,M,NaN,36.5,1,2025-03-18 19:10:00,0.00,...,36.50,3,2025,1,Masculine,Underwear and Pajamas,Men'S Underwear Lightweight Fabric For Extra C...,NaN,M|L|XL|XXL,11.14
6416826,INV-PT-035-01497759,1,1639026,17424,M,NaN,25.5,1,2025-03-18 19:11:00,0.35,...,16.57,3,2025,1,Feminine,Shirts and Blouses,Hand -Embroidered Female Blouse,NaN,S|M|L,3.42

In [35]:
df = df.merge(df_stores, on = 'store_id', how = 'left')
df

,invoice_id,line,customer_id,product_id,size,color_x,unit_price,quantity,date,discount,...,color_y,sizes,production_cost,country,city,store_name,number_of_employees,zip_code,latitude,longitude
0,INV-US-001-03558761,1,47162,485,M,NaN,80.5,1,2023-01-01 15:42:00,0.00,...,NaN,M|L|XL,12.09,United States,New York,Store New York,10,10001,40.7128,-74.0060
1,INV-US-001-03558761,2,47162,2779,G,NaN,31.5,1,2023-01-01 15:42:00,0.40,...,NaN,P|M|G,15.14,United States,New York,Store New York,10,10001,40.7128,-74.0060
2,INV-US-001-03558761,3,47162,64,M,NEUTRAL,45.5,1,2023-01-01 15:42:00,0.40,...,NEUTRAL,M|L|XL|XXL,12.02,United States,New York,Store New York,10,10001,40.7128,-74.0060
3,INV-US-001-03558762,1,10142,131,M,BLUE,70.0,1,2023-01-01 20:04:00,0.40,...,BLUE,S|M|L|XL,49.28,United States,New York,Store New York,10,10001,40.7128,-74.0060
4,INV-US-001-03558762,2,10142,716,L,WHITE,26.0,1,2023-01-01 20:04:00,0.00,...,WHITE,M|L|XL,8.31,United States,New York,Store New York,10,10001,40.7128,-74.0060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6416822,INV-PT-035-01497756,2,1640168,15414,P,NaN,35.5,1,2025-03-18 08:52:00,0.35,...,NaN,P|M|G|GG,3.67,Portugal,Coimbra,Store Coimbra,7,3000-001,40.2056,-8.4196
6416823,INV-PT-035-01497756,3,1640168,15232,G,RED,51.5,1,2025-03-18 08:52:00,0.35,...,RED,P|M|G,26.46,Portugal,Coimbra,Store Coimbra,7,3000-001,40.2056,-8.4196
6416824,INV-PT-035-01497757,1,1636770,15401,XL,NaN,40.0,1,2025-03-18 19:01:00,0.00,...,NaN,S|M|L|XL,6.92,Portugal,Coimbra,Store Coimbra,7,3000-001,40.2056,-8.4196
6416825,INV-PT-035-01497758,1,1642472,15671,M,NaN,36.5,1,2025-03-18 19:10:00,0.00,...,NaN,M|L|XL|XXL,11.14,Portugal,Coimbra,Store Coimbra,7,3000-001,40.2056,-8.4196
6416826,INV-PT-035-01497759,1,1639026,17424,M,NaN,25.5,1,2025-03-18 19:11:00,0.35,...,NaN,S|M|L,3.42,Portugal,Coimbra,Store Coimbra,7,3000-001,40.2056,-8.4196

In [36]:
df = df.drop(['size','color_x','color_y','sizes'],axis=1)

In [37]:

df.to_csv('../data/clean/Data_cleaning_wrangling.csv',index=False)

In [38]:
df.columns

Index(['invoice_id', 'line', 'customer_id', 'product_id', 'unit_price',
       'quantity', 'date', 'discount', 'line_total', 'store_id', 'employee_id',
       'currency', 'currency_symbol', 'sku', 'transaction_type',
       'payment_method', 'invoice_total', 'Month', 'Year', 'Day', 'category',
       'sub_category', 'description_en', 'production_cost', 'country', 'city',
       'store_name', 'number_of_employees', 'zip_code', 'latitude',
       'longitude'],
      dtype='str')

In [39]:
df['currency'].unique()

<StringArray>
['USD', 'CNY', 'EUR', 'GBP']
Length: 4, dtype: str

In [40]:
# generate cleaned csv 
# add utf-8 format 


df_customers.to_csv('../data/clean/customers_cleaned.csv', encoding = 'utf-8')
df_discounts.to_csv('../data/clean/discounts_cleaned.csv', encoding = 'utf-8')
df_employees.to_csv('../data/clean/employees_cleaned.csv', encoding = 'utf-8')
df_products.to_csv('../data/clean/products_cleaned.csv', encoding = 'utf-8')
df_stores.to_csv('../data/clean/stores_cleaned.csv', encoding = 'utf-8')
df_transactions.to_csv('../data/clean/transactions_cleaned.csv', encoding = 'utf-8')

In [41]:
# library joblib